// Market Hub mobile data — directional (bull/neutral/bear), no 0-10 scores.
// Each card: status, 3 inline KPIs (rows), a charted headline metric, and stat boxes.
window.GLANCE = {
  asOf: 'Mar 14',
  exec: { label: 'Risk-On', posture: 'Broad-based bullish across most dimensions', bull: 7, neutral: 2, bear: 1 },
  // Each category's cards carry only a directional status — the dots ARE the read.
  categories: [
    { label: 'Trend',         weight: '40%', cards: ['bullish', 'bullish', 'bullish'] },
    { label: 'Participation', weight: '35%', cards: ['neutral', 'bullish', 'bullish'] },
    { label: 'Macro',         weight: '25%', cards: ['bearish', 'neutral', 'bullish', 'neutral'] },
  ],
  groups: [
    { label: 'Market Structure', ids: ['regime', 'leadership', 'breadth'] },
    { label: 'Macro Pricing',    ids: ['valuations', 'yield', 'credit', 'currency'] },
    { label: 'Flow & Rotation',  ids: ['globalflows', 'sectors'] },
    { label: 'Real Assets',      ids: ['commodities', 'equities'] },
    { label: 'Crowd Intelligence', ids: ['crowdsignals', 'positioning'] },
  ],
  cards: {
    regime: { id: 'regime', title: 'Regime', status: 'bullish', seed: 11, trend: 0.7, metric: 'SPY vs 200-day SMA', metricVal: '+8.4%', metricUnit: '% above',
      stats: [['Percentile Rank', '94th', 'of all history', 'pos'], ['Regime Duration', '412d', 'above 200d SMA'], ['Extension', '+1.8%', '10d ROC', 'pos']],
      rows: [['SPY vs 200d SMA', '+8.4%', 'extended above', 'bullish'], ['200d slope', '+0.12%/d', 'rising', 'bullish'], ['RSI (14)', '58.2', 'mid-range', 'neutral'], ['Days since cross', '412', 'durable trend', 'bullish']] },
    leadership: { id: 'leadership', title: 'Leadership', status: 'bullish', seed: 23, trend: 0.5, metric: 'RSP / SPY ratio', metricVal: '+3.2%', metricUnit: 'cumulative',
      stats: [['Breadth Spread', '+3.2%', 'RSP vs SPY', 'pos'], ['Daily Streak', '6', 'RSP wins', 'pos'], ['Tech Spread', '+1.1%', 'QQEW vs QQQ', 'pos']],
      rows: [['RSP / SPY ratio', '+3.2%', 'broadening', 'bullish'], ['QQEW / QQQ', '+1.1%', 'tech broad', 'bullish'], ['Adv/Decl line', '1.4', 'steady', 'neutral']] },
    breadth: { id: 'breadth', title: 'Breadth', status: 'neutral', seed: 37, trend: 0.1, metric: '% of NYSE above 200d', metricVal: '62%', metricUnit: 'above 200d',
      stats: [['$MMTH (200d)', '62%', '% above 200d'], ['$MMFI (50d)', '54%', '% above 50d'], ['Days in Zone', '23', 'at level']],
      rows: [['% above 200d', '62%', 'moderate', 'neutral'], ['% above 50d', '54%', 'cooling', 'neutral'], ['New highs', '186', 'expanding', 'bullish'], ['New lows', '94', 'creeping up', 'bearish']] },
    valuations: { id: 'valuations', title: 'Valuations', status: 'bearish', seed: 41, trend: 0.6, metric: 'Shiller CAPE', metricVal: '36.2', metricUnit: 'ratio',
      stats: [['Shiller CAPE', '36.2', '94th pctile', 'neg'], ['Buffett Ratio', '198%', 'cap / GDP', 'neg'], ['Trailing P/E', '27.4', '88th pctile', 'neg']],
      rows: [['Shiller CAPE', '36.2', 'historically rich', 'bearish'], ['Buffett Indicator', '198%', 'far above avg', 'bearish'], ['Fwd P/E', '22.1', 'elevated', 'neutral']] },
    yield: { id: 'yield', title: 'Yield', status: 'neutral', seed: 53, trend: -0.2, metric: '30-year Treasury yield', metricVal: '4.62%', metricUnit: 'yield',
      stats: [['30yr Yield', '4.62%', 'long-bond'], ['SHY', '+0.1%', '2yr ETF, 5d'], ['10yr Yield', '4.28%', 'benchmark rate']],
      rows: [['30yr yield', '4.62%', 'range-bound', 'neutral'], ['SHY vs 200d', '+0.2%', 'rising · Fed hawkish', 'bearish'], ['10yr yield', '4.28%', 'above 200d · rising', 'bearish'], ['2s10s curve', '+34bp', 'normalizing', 'neutral']] },
    credit: { id: 'credit', title: 'Credit', status: 'bullish', seed: 67, trend: 0.4, metric: 'High-yield spread', metricVal: '298bp', metricUnit: 'spread',
      stats: [['HY Spread', '298bp', 'tight vs history', 'pos'], ['HYG vs 50d', '+1.4%', 'high-yield ETF', 'pos'], ['HYG / LQD', '+0.8%', 'risk appetite', 'pos']],
      rows: [['HY spread', '298bp', 'tightening', 'bullish'], ['HYG vs 50d', '+1.4%', 'above', 'bullish'], ['LQD vs 50d', '+0.2%', 'flat', 'neutral']] },
    globalflows: { id: 'globalflows', title: 'Global Flows', status: 'bullish', seed: 71, trend: 0.45, metric: 'Markets above 200d', metricVal: '10/13', metricUnit: 'of 13',
      stats: [['Above 200d', '10/13', 'global markets', 'pos'], ['DM Breadth', '88%', 'developed', 'pos'], ['EM Breadth', '60%', 'emerging']],
      flags: ['us', 'gb', 'de', 'fr', 'jp', 'cn', 'in', 'br', 'au', 'ca', 'kr', 'hk', 'mx'],
      rows: [['Developed (DM)', '7/8', 'broad', 'bullish'], ['Emerging (EM)', '3/5', 'mixed', 'neutral'], ['ACWI vs 200d', '+6.1%', 'above', 'bullish']] },
    sectors: { id: 'sectors', title: 'Sectors', status: 'bullish', seed: 83, trend: 0.55, metric: 'Cyclicals vs defensives', metricVal: '+2.6%', metricUnit: '1mo',
      stats: [['Cyclical Lead', '+2.6%', 'cyc vs def', 'pos'], ['XLK vs SPY', '+1.9%', 'tech', 'pos'], ['XLU vs SPY', '−1.2%', 'utilities', 'neg']],
      rows: [['Discr./Staples', '+2.6%', 'risk-on', 'bullish'], ['Semis (SMH)', '+3.4%', 'leading', 'bullish'], ['Energy (XLE)', '+0.1%', 'flat', 'neutral']] },
    commodities: { id: 'commodities', title: 'Commodities', status: 'bullish', seed: 91, trend: 0.3, metric: 'USCI vs 200-day', metricVal: '+4.2%', metricUnit: '% above',
      stats: [['Copper/Gold', '+1.1%', 'growth proxy', 'pos'], ['USCI vs 200d', '+4.2%', 'broad cmdty', 'pos'], ['Gold', '$2,164', '+0.6% 5d']],
      rows: [['Copper (HG)', '+2.3%', 'firming', 'bullish'], ['USCI vs 200d', '+4.2%', 'above', 'bullish'], ['Crude (WTI)', '$78.4', 'range-bound', 'neutral']] },
    equities: { id: 'equities', title: 'Equities', status: 'bullish', seed: 97, trend: 0.5, metric: 'Watchlist above 200d', metricVal: '21/24', metricUnit: 'of 24',
      stats: [['Above 50d', '18/24', 'watchlist', 'pos'], ['Above 200d', '21/24', 'watchlist', 'pos'], ['Avg RSI', '61.4', 'momentum']],
      rows: [['AI / semis basket', '6/6', 'all above MA', 'bullish'], ['Megacap tech', '7/7', 'leading', 'bullish'], ['Small-cap (IWM)', '+0.4%', 'lagging', 'neutral']] },
    currency: { id: 'currency', title: 'Currency', status: 'neutral', seed: 103, trend: -0.1, metric: 'US Dollar Index', metricVal: 'UUP', metricUnit: 'vs 200-day SMA',
      stats: [['UUP vs 200d', '+0.8%', 'USD firm', 'neg'], ['FXE vs 200d', '−1.2%', 'EUR softening'], ['FXY vs 200d', '−0.6%', 'JPY carry open']],
      rows: [['UUP (Dollar)', '+0.8%', 'above 200d · tightening', 'bearish'], ['FXE (Euro)', '−1.2%', 'below 200d · risk soft', 'bearish'], ['FXY (Yen)', '−0.6%', 'below 200d · carry open', 'neutral'], ['FX Regime', 'Mixed', 'no dominant pattern', 'neutral']],
      note: 'The three major currency indices — DXY (Dollar), EXY (Euro), and JXY (Yen) — form a macro triangulation system. A weaker Dollar alongside a stronger Euro and weaker Yen signals open global liquidity and risk appetite. Dollar strength with falling Euro and Yen points to a global liquidity squeeze. A sudden violent Yen surge, regardless of Dollar direction, signals a systemic carry-trade unwind — one of the most dangerous short-term shocks for risk assets. When all three are quiet, equity returns revert to earnings fundamentals and sector rotation.' },
    crowdsignals: { id: 'crowdsignals', title: 'Crowd Signals', status: 'neutral', seed: 109, trend: 0.0, metric: 'Prediction Markets', metricVal: '—', metricUnit: 'Kalshi · Polymarket',
      stats: [['FOMC Action', '—', 'Next FOMC decision', null], ['FOMC Confidence', '—', '% at implied rate', null], ['CPI Consensus', '—', 'MoM estimate', null]],
      rows: [['FOMC Rate', '—', 'Awaiting live data', 'neutral'], ['CPI Outlook', '—', 'Awaiting live data', 'neutral'], ['Crowd Bias', '—', 'Polymarket signals', 'neutral']],
      note: 'Live consensus from Kalshi prediction markets (FOMC rate, CPI) and Polymarket macro signals. Data reflects current market-implied probabilities for near-term macro events.' },
    positioning: { id: 'positioning', title: 'Positioning', status: 'neutral', seed: 115, trend: 0.0, metric: 'COT Net Position', metricVal: '—', metricUnit: 'CFTC weekly · 3Y pctile',
      stats: [['S&P 500 (ES)', '—', 'Net speculative pctile', null], ['Gold (GC)', '—', 'Net speculative pctile', null], ['WTI Crude (CL)', '—', 'Net speculative pctile', null]],
      rows: [['S&P Futures (ES)', '—', 'Awaiting live data', 'neutral'], ['Gold (GC)', '—', 'Awaiting live data', 'neutral'], ['WTI Crude (CL)', '—', 'Awaiting live data', 'neutral']],
      note: 'CFTC Commitment of Traders — weekly institutional positioning vs. 3-year range. Contrarian signal: extreme speculative crowding (≥80th or ≤20th pctile) tends to precede reversals.' },
  },
};
